name: csp-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
 - bison
 - brotli
 - bump2version>=1
 - cmake
 - codespell
 - compilers
 - cyrus-sasl
 - exprtk
 - flex
 - python-graphviz
 - gtest
 - httpx
 - isort
 - libarrow=15
 - librdkafka
 - lz4-c
 - mamba
 - mdformat
 - ninja
 - numpy
 - psutil
 - pyarrow=15
 - pandas
 - pillow
 - polars
 - pytz
 - pytest
 - pytest-cov
 - pytest-sugar
 - pytest-asyncio
 - python<3.12
 - python-rapidjson
 - rapidjson
 - requests
 - ruamel.yaml
 - ruff
 - scikit-build
 - slack-sdk
 - sqlalchemy
 - tar
 - tornado
 - twine
 - unzip
 - wheel
 - zip
