name: csp
channels:
  - conda-forge
  - nodefaults
dependencies:
 - astor
 - bison
 - brotli
 - bump-my-version
 - cmake
 - codespell>=2.4,<2.5
 - compilers
 - cyrus-sasl
 - deprecated
 - docutils<0.22.1
 - exprtk
 - fastapi
 - flex
 - graphviz
 - gtest
 - httpx>=0.20,<1
 - libarrow<24
 - libboost>=1.80.0
 - libboost-headers>=1.80.0
 - librdkafka
 - lz4-c
 - make
 - mamba
 - mdformat>=0.7.19,<1.1
 - mdformat-tables>=1,<1.1
 - ninja
 - numpy>=2
 - pandas
 - pillow
 - polars
 - psutil
 - pyarrow>=15,<24
 - pydantic>=2
 - pytest
 - pytest-asyncio
 - pytest-cov
 - pytest-sugar
 - python>=3.10,<3.14
 - python-build
 - python-graphviz
 - python-rapidjson
 - pytz
 - rapidjson
 - requests
 - ruamel.yaml
 - ruff>=0.9,<0.15
 - scikit-build
 - setuptools>=69,<74
 - sqlalchemy
 - tar
 - threadpoolctl
 - tornado
 - twine
 - typing-extensions
 - unzip
 - uvicorn
 - wheel
 - zip
 - zlib
