name: csp
channels:
  - conda-forge
  - nodefaults
dependencies:
 - bison
 - brotli
 - build
 - bump2version>=1
 - cmake
 - codespell>=2.2.6,<2.3
 - compilers
 - cyrus-sasl
 - deprecated
 - exprtk
 - flex
 - graphviz
 - python-graphviz
 - gtest
 - httpx>=0.20,<1
 - isort>=5,<6
 - libarrow=16
 - libboost>=1.80.0
 - libboost-headers>=1.80.0
 - librdkafka
 - lz4-c
 - mamba
 - mdformat>=0.7.17,<0.8
 - ninja
 - numpy<2
 - pandas
 - pillow
 - polars
 - psutil
 - pyarrow=16
 - pytz
 - pytest
 - pytest-asyncio
 - pytest-cov
 - pytest-sugar
 - python<3.13
 - python-rapidjson
 - rapidjson
 - requests
 - ruamel.yaml
 - ruff>=0.3,<0.4
 - scikit-build
 - sqlalchemy
 - tar
 - threadpoolctl
 - tornado
 - twine
 - unzip
 - wheel
 - zip
